logging:
  level:
    root: info

server:
  servlet:
    context-path: /vamak/api

spring:
  datasource:
    url: jdbc:h2:mem:vamak;INIT=CREATE SCHEMA IF NOT EXISTS vamak
    username: sa
    password: sa
    name: vamak
    generate-unique-name: false

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        show_sql: true
        format_sql: true